version: '3'
services:
    app:
        container_name: app
        image: golang:1.20.13-bullseye
        build: ./app
        ports:
            - 3005:3001
        volumes:
            - ./app:/root/app
            - ./gin_goth/auth_grpc:/root/app/auth_grpc
        tty: true
        restart: always
        depends_on:
            - redis

    gin_goth:
        container_name: auth_Server
        image: golang:1.20.13-bullseye
        build: ./gin_goth
        ports:
            - 3000:3000
        volumes:
            - ./gin_goth:/root/gin_goth
        tty: true
        restart: always
        depends_on:
            - redis

    redis:
        container_name: redis
        image: "redis:latest"
        ports:
            - "6379:6379"
        restart: always

    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        ports:
            - "8443:80"
        volumes:
            # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
        tty: true
        
        extra_hosts:
            - host.docker.internal:host-gateway